databases:
  - name: GithubBattle_DB
    databaseName: github_battle_db
    user: GithubBattle
    region: singapore

services:
  - type: web
    name: GithubBattle
    env: ruby
    region: singapore
    plan: starter
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: GithubBattle
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
  - type: cron
    name: Github-battle
    env: ruby
    plan: starter
    region: singapore
    buildCommand: ./bin/render-build.sh
    startCommand: bundle exec rails runner "puts 'Hello'"
    schedule: 0 6 * * *
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: GithubBattle
          property: connectionString
